### ISSUE TITLE
Could not load file or assembly '/HelloWorld.dll'

### ISSUE THREAD

**Issue by cameronkerrnz** [carlosalexei/aks-workshop#4]
Building the container image works okay, but when running:

```
ckerr@Camerons-Air HelloWorld % docker run -it -p 8080:80 helloworld:latest
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly '/HelloWorld.dll'. The system cannot find the file specified.

File name: '/HelloWorld.dll'
^C
```

Here's a working version of the Dockerfile. I think the two significant changes are:

* you should include the matching tag on the runtime container used
* possibly the location of where you publish application to needs to be the same as when you build

```Dockerfile
# Define base image that includes dev tools
FROM mcr.microsoft.com/dotnet/sdk:6.0 as DevEnv

# Create a folder
WORKDIR /source

# Copy the project file
COPY *.csproj ./

# Restore dotnet libraries for the project
RUN dotnet restore

# Copy all application files
COPY . ./

# Compile project and create production binaries
RUN dotnet publish -c Release -o /app

# Download another images with aspnet runtime
FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app

# Copy from the first image (DevEnv) binaries
COPY --from=DevEnv /app ./

# Define the process to be executed in the container
ENTRYPOINT [ "dotnet", "HelloWorld.dll" ]
```

Compare with https://docs.microsoft.com/en-nz/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-6.0

```
ckerr@Camerons-Air HelloWorld % docker version
Client:
 Version:           20.10.16
Server: Docker Desktop 4.9.1 (81317)
  Version:          20.10.16
```

```
ckerr@Camerons-Air HelloWorld % git log
commit 6e49b5600e1f2e54e12bb99fddc721f21669d4be (HEAD -> main, origin/main, origin/HEAD)
Author: Carlos A. Marquez <carlos.marquez@microsoft.com>
Date:   Tue May 24 20:38:55 2022 -0700

    Update HelloWorld.csproj

    Update .NET version require by the project
```

**Comment by carlosalexei** [comment]
Hi @cameronkerrnz, thanks for creating this issue. In your Dockerfile, you have a WORKDIR /app after the second FROM clause. That will make the /app directory and also would move you to such a directory. When you COPY --from=DevEnv, the binary HelloWorld.dll will be copied to the /app directory instead of the root directory. If you remove the second WORKDIR /app, your container will start properly. Another option is to provide the full path to the HelloWorld.dll as the parameter on the ENTRYPOINT.

**Comment by carlosalexei** [comment]
Hi @cameronkerrnz,
Feedback taken, I will add the tag to the second FROM. I think it's a good practice to include the tag. During the transition from version 5.0 to version 6.0 some people experienced conflicts when using version 5.0 to build and using version 6.0 (latest) to run as the original project was set for 5.0. 

You should not have any problems by building your images in any platform (Mac, Linux or Windows) 

Thanks!
